version: "3.9"

services:
  server:
    restart: unless-stopped
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - HASH_SALT=${HASH_SALT}
    build: .
    ports:
      - "3000:3000"